language: node_js
node_js:
- node

install:
  - npm install -g babel-cli
  - yarn
script:
  - yarn run build
deploy:
  provider: npm
  email: frontend@synchro.com.br
  api_key:
    secure: kqJDCjVDWAIdNAXe2QyccGUC4evTfNg86mIAv0jcSLeMW2bX8mA9gK1qwVa1F5CRwByh1hixptMFyHNFK8sRErPfYptZ+5LmzzuQAqSMiBGFC6sZDn3PuBedQBdIfKtjydjJnlLZvkrym4v2aKbrul7sJJQsfPI4xRCGZ3cEc235PcvJUPSh7j7d9o+lvsnSMyLegxSoH5hXtb08XwdFaDPNQlXsuMXRAi9Zw8lX+8op0k2wVhzcQGjwHe11Z5vHNg4MQm3vXTkyCXF+4GnIUt+k81FCNPAWbZ1GKPibM0gparR8zjZsLSERZaIbDjdXlV7HhW3+LlcNZQrEcHU1pSKWgpAdR0DxpLrE/OgZnMQA1AoXmAi5VN6D1lty7PfW+rHtgp/Nmj6rEZY6UUE+4MlIqqMwOyt3GPB+xp9KY48x2ey/GhFt6NAb2t8sBPM/ej8bkSVn5x4DYrdERg607otoexXnKojFKHM1g/9VYwqljDnbsziVCA/5QTHHg3Nxj/z51mNyAxubgtxbACibZ8Mqz5Cqcv3/exHc/ypAcobsntk0NGawXwZkan1x1gRDjTcux0YNaTCJNJXxo1NwZlv7vA2q3A8JOC+T+0AiLViCJrcv/WkWj0ZrYmH56sHKADMXvV+fbQmKnfYIU15gbgPvt8rOddd4xWPP/Mq0Jik=
  on:
    tags: true
    repo: Synchro-TEC/apollo-11
